core_backgrounds = [
    {'background': 'Archaeologist',
     'description': 'You study Syrneth ruins and explore the lost parts of Terra.',
     'quirk': 'Earn a Hero Point when you turn an artifact of value over to a university, museum, or a publicly displayed site.',
     'advantages': ['Signature Item', 'Eagle Eyes'],
     'skills': ['Athletics', 'Convince', 'Notice', 'Scholarship', 'Theft'],
     'nationality_restriction': None,
     'duelist_style': None},
    {'background': 'Aristocrat',
     'description': 'You were born into the nobility of your home country and regularly attend the courts.',
     'quirk': 'Earn a Hero Point when you prove there is more to nobililty than expensive clothes and attending court.',
     'advantages': ['Rich', 'Disarming Smile'],
     'skills': ['Aim', 'Convince', 'Empathy', 'Ride', 'Scholarship'],
     'nationality_restriction': None,
     'duelist_style': None},
]
pirate_backgrounds = [
    {'background': 'Atabean Rook',
     'description': 'You may not be royalty, but the alleys of Fort Freedom are your kingdom; its forgotten urchins are your subjects.',
     'quirk': 'Earn a Hero Point when you use your reputation or status to help another character.',
     'advantages': ['Salty Dog', 'Eye for Talent'],
     'skills': ['Intimidate', 'Sailing', 'Theft', 'Warfare', 'Weaponry'],
     'nationality_restriction': None,
     'duelist_style': None},
    {'background': 'Company Escapee',
     'description': "You escpaed the ATC's clutches and now strive to make every day the Company exists more costly than yesterday.",
     'quirk': "Earn a Hero Point when you subvert the Company's plans or sabotage its income stream.",
     'advantages': ['Duelist Academy', 'Valiant Spirit'],
     'skills': ['Athletics', 'Brawl', 'Hide', 'Notice', 'Theft'],
     'nationality_restriction': None,
     'duelist_style': 'Jogo de Dentro'},
]
