core_nationalities = [
    {'nationality': 'Avalon',
     'bonus_traits': ['Panache', 'Resolve']},
    {'nationality': 'Inismore',
     'bonus_traits': ['Panache', 'Wits']},
    {'nationality': 'The Highland Marches',
     'bonus_traits': ['Brawn', 'Finesse']},
    {'nationality': 'Castille',
     'bonus_traits': ['Finesse', 'Wits']},
    {'nationality': 'Eisen',
     'bonus_traits': ['Brawn', 'Resolve']},
    {'nationality': 'Montaigne',
     'bonus_traits': ['Finesse', 'Panache']},
    {'nationality': 'Sarmatia',
     'bonus_traits': ['Brawn', 'Panache']},
    {'nationality': 'Ussura',
     'bonus_traits': ['Resolve', 'Wits']},
    {'nationality': 'Vesten',
     'bonus_traits': ['Brawn', 'Wits']},
    {'nationality': 'Vodacce',
     'bonus_traits': ['Finesse', 'Resolve']},
]
pirate_nationalities = [
    {'nationality': 'Aragosta',
     'bonus_traits': ['Panache', 'Finesse']},
    {'nationality': 'Jaragua',
     'bonus_traits': ['Brawn', 'Finesse']},
    {'nationality': 'La Bucca',
     'bonus_traits': ['Panache', 'Wits']},
    {'nationality': 'Numa',
     'bonus_traits': ['Resolve', 'Wits']},
    {'nationality': 'Rahuri',
     'bonus_traits': ['Brawn', 'Resolve']},
]
